### ISSUE TITLE
Openmod Dont load

### ISSUE THREAD

**Issue by Senior-S** [openmod/openmod#103]
I installed the latest version (0.9.63) and openmod dont load, in the log nothing references openmod, in the folder modules i have openmod and avirockets. I deleted the old folder of openmod to a new installation but openmod dont load in any case.

**Comment by Trojaner** [comment]
- Remove any other module

**Comment by Senior-S** [comment]
Ok, i trying to remove the avirockets module and nothing.

I attached the log of the server with the OpenMod module. 
[Server_Default.log](https://github.com/openmod/openmod/files/4883754/Server_Default.log)

and the parameters to launch the server: D:\Juegos\steamapps\common\U3DS\Unturned.exe -nographics -batchmode +secureserver/Default

**Comment by Trojaner** [comment]
What does your Modules folder and the OpenMod.Unturned folder inside look like

**Comment by Senior-S** [comment]
Modules folder: https://imgur.com/UVBxonV

Openmod.Unturned: https://imgur.com/pqszo9P

**Comment by Trojaner** [comment]
I have no idea why it doesnt work for you and without any errors there is not much I could do

**Comment by Senior-S** [comment]
Ok, i found the error, for any reason when i downloaded the module (before) the folder ared not completed and have 149 items, after i re-downloaded the module and now have 194 items, for any reason the first time i downloaded a corrupt .zip
