### ISSUE TITLE
Actors Should Apply To SubCommands

### ISSUE THREAD

**Issue by Kr4ken-9** [openmod/openmod#108]
Sort of like https://github.com/openmod/openmod/pull/74:

If I have a command for example `/home`, obviously the console cannot `/home` anywhere.
However, if I have a command `/home list`, the console could take advantage of this command.

There are probably other examples of this too

**Comment by Trojaner** [comment]
Makes sense

**Comment by Trojaner** [comment]
Making this would be too complicated and causes issues like e.g. /home not showing up in help. Marking as wontfix and keeping it as intentional design choice for now.
