### ISSUE TITLE
Unturned Console Input Bug

### ISSUE THREAD

**Issue by Trojaner** [openmod/openmod#11]
When writing or pressing backspace, it clears the upper line. Probably related to overriding Unturned's input handling [here](https://github.com/openmod/OpenMod/blob/master/unturned/OpenMod.Unturned/Logging/SerilogConsoleInputOutput.cs) and [here](https://github.com/openmod/OpenMod/blob/master/unturned/OpenMod.Unturned/Logging/SerilogWindowsConsoleInputOutput.cs). Needs investigation.

**Comment by Trojaner** [comment]
![2020-06-18_15-33-03](https://user-images.githubusercontent.com/1809172/85020474-12099b00-b179-11ea-96c5-ca354a4953bb.gif)

**Comment by rube200** [comment]
This should be reopened, i found a bug:
Every time a press tab, it create a tab space and a new line

[Video](https://streamable.com/iprev3)

**Comment by rube200** [comment]
and more 1

[Video2](https://streamable.com/d2p1tx)

**Comment by Arechii** [comment]
Console.CursorTop is incremented improperly for exceptions it seems

**Comment by Trojaner** [comment]
Can you please check again. I incremented CursorTop as much as lines printed.

**Comment by DiFFoZ** [comment]
Still has this problem

![GyasWpDbBl](https://user-images.githubusercontent.com/48765566/85945197-5578bc00-b966-11ea-9654-b57ab6e445f3.gif)

**Comment by rube200** [comment]
I'm currently working on a fix for it, but I'm not sure why the console spam these empty lines when the server starts
