### ISSUE TITLE
Testing on Linux

### ISSUE THREAD

**Issue by Trojaner** [openmod/openmod#12]
Before releasing, we need to test if OpenMod for Unturned works on Linux.

**Comment by Johnanater** [comment]
I placed the latest release's folder in the Modules folder, though I don't see anything in the logs.

On Ubuntu 20.04 LTS.

**Comment by Trojaner** [comment]
Latest version is currently broken in general, I will fix it soon

**Comment by Trojaner** [comment]
Hey, can you please test with v0.9.17?

**Comment by Johnanater** [comment]
It starts now, but there is an error initializing nexus:
https://pastebin.com/2WvWq0EA

**Comment by Trojaner** [comment]
Doesn't sound good. Might be related to the NuGet library

**Comment by Trojaner** [comment]
Is your "HOME" environment variable set? @Johnanater

**Comment by Trojaner** [comment]
Can you please test again with v0.9.18

**Comment by Johnanater** [comment]
Just tested on v0.9.23, more errors
https://pastebin.com/2Q8JZcq3

**Comment by Trojaner** [comment]
The problem occurs when [`NuGetEnvironment.GetFolderPath(NuGetFolderPath)`](https://github.com/NuGet/NuGet.Client/blob/cdf58815319ec0c9d1a29c3c790233826c1bab8a/src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs#L19) is called with `NuGetFolderPath.MachineWideSettingsBaseDirectory`.

![image](https://user-images.githubusercontent.com/1809172/85857616-e0b94c80-b7c2-11ea-91ec-a510460b98ba.png)

machineWideBaseDir is seems to be null, and for Linux, NuGet grabs it by calling `machineWideBaseDir = GetFolderPath(SpecialFolder.CommonApplicationData)`.

![image](https://user-images.githubusercontent.com/1809172/85857702-00e90b80-b7c3-11ea-8496-4e64b94ab671.png)

This is where the interesting part begins, because according to this code it can be null.
That's the confusing part.

**Comment by Johnanater** [comment]
Same issue on v0.9.27
https://pastebin.com/XMtvLZQ4

A Harmony patch would probably be the best workaround for now

**Comment by Trojaner** [comment]
Can you test again with 0.9.30?

**Comment by Johnanater** [comment]
Still an issue on 0.9.37
https://pastebin.com/Qq1HQgYg

**Comment by Trojaner** [comment]
Can you test with 0.9.38?

**Comment by Trojaner** [comment]
Ok so the issue was actually something else: NuGet thinks its running on Windows because RuntimeInformation.IsOSPlatform returns true when checked against Windows - while running on Linux.

This is fixed now, got a new error:

![image](https://user-images.githubusercontent.com/1809172/86118296-3babb600-bad9-11ea-93bc-4c934b0bf30d.png)
 Which is also fixed now.
