### ISSUE TITLE
Delete Outdated Nuget Packages

### ISSUE THREAD

**Issue by IAmSilK** [openmod/openmod#125]
Currently, old packages are left after they've been updated.

**Comment by Trojaner** [comment]
After thinking about it, this shouldn't be done. Different plugins may depend on different versions of libraries. #133 should be done instead so it resolves correct package. I am not sure tho. NuGet solves this problem by always prefering the newer version if two conflicting dependencies exist.

**Comment by Trojaner** [comment]
No longer planned. Plugins might depend on conflicting versions of libraries and this would break one in that case.
