### ISSUE TITLE
NuGet: Resolve nearest (or newest) assembly if no exact match is found

### ISSUE THREAD

**Issue by Trojaner** [openmod/openmod#133]
https://github.com/openmod/openmod/blob/master/framework/OpenMod.NuGet/NuGetPackageManager.cs#L418

**Comment by rube200** [comment]
What do u mean?

**Comment by Trojaner** [comment]
Multiple versions of a NuGet package can be installed at the same time. If an assembly dependency gets resolved, currently NuGet will resolve it to a random version (`matchingAssemblies.FirstOrDefault()`), which is wrong. It should resolve to the nearest or newest version it can find instead.

**Comment by rube200** [comment]
can this solve?
```cs
var result = (Assembly)matchingAssemblies.FirstOrDefault(d => d.Version >= parsedVersion)?.Assembly.Target;
```

**Comment by Trojaner** [comment]
No, because:
Assume the plugin wants 1.0.1 and 1.0.0 and 2.0.0 is installed. In this case, 1.0.0 should be used and not 2.0.0. See the link I have added to my second post.
