### ISSUE TITLE
OM reload

### ISSUE THREAD

**Issue by rube200** [openmod/openmod#145]
Sometimes openmod doesn't load after a reload the causes are still unknown.
The causes appear to be random as it happens with or without players on the server, and when the command is executed by the console or by the player.

**Comment by DiFFoZ** [comment]
I think the problem is here

https://github.com/openmod/openmod/blob/c539c3454719d6de8f990c7aef1087a222153a29/framework/OpenMod.Runtime/Runtime.cs#L119-L121

**Comment by rube200** [comment]
Looks like its working, it is just LoadPPluginAssembliesAsync() that take a lot of time without any output, feedback

**Comment by Trojaner** [comment]
Please reopen if it still occurs
