### ISSUE TITLE
Unable to Write Console Input, only happens when using openmod

### ISSUE THREAD

**Issue by M0RG4N01** [openmod/openmod#147]
Hey :) 

So I am having an issue with openmod, currently I am using TCAdmin (a game control panel) to host Unturned Servers, this uses WriteConsoleInput so that it can send commands to console: [See here](https://docs.microsoft.com/en-us/windows/console/writeconsoleinput)

This works perfectly fine with sending commands to an Unturned server without modules and when using the Rocket.Unturned module on the Unturned server it will executes commands perfectly as expected. However, when using openmod the commands are sent to the console but not executed as normal like with RocketMod installed or just an Unturned server with no modules: 

![image](https://user-images.githubusercontent.com/19923469/88612567-67dc3780-d083-11ea-9665-9fac8a8086c7.png)

This only happens when using openmod, is there anything you can do about this? I am happy to help you look into this issue further and provide you with places you can test for yourself or anymore information you may need :) 

Tested on:
OS; Windows Server 2012R2
.NET Version:  4.7.2 
CP; TCAdmin

**Comment by Trojaner** [comment]
Interesting. Does this happen for all commands?

**Comment by M0RG4N01** [comment]
Yeah its for all commands, also sounds great i'm glad you'll look into it enjoy the rest of your vacation 👍

**Comment by Trojaner** [comment]
Please let me know if the attached build fixes it. Keep in mind that this is a debug build which should only be used for testing purposes.
[openmod2debug.zip](https://github.com/openmod/openmod/files/5133083/openmod2debug.zip)
