### ISSUE TITLE
`.Trim()` does not trim all whitespace characters

### ISSUE THREAD

**Issue by Pustalorc** [openmod/openmod#148]
This affects any command execution.

Replication instructions:
Step 1: Write a whitespace character other than the standard space. In Windows you can hold alt and press 9 on the number pad, this will write the `character tabulation`.
Step 2: Type any command after the whitepsace character
Step 3: Press enter

Note: Putting the whitespace after the command still does the same thing.

Witness the `Command was not found:` error appear due to the whitespace not being trimmed by `.Trim()`

See images attached of tests done by me and _Rube200:
![image](https://user-images.githubusercontent.com/17557714/88665411-ddc1bc80-d0de-11ea-9b96-32875464a8b5.png)
![image](https://user-images.githubusercontent.com/17557714/88665413-e0bcad00-d0de-11ea-95a7-7a9c44ef475e.png)

**Comment by Trojaner** [comment]
string result = string.Concat(source.Where(c => !char.IsWhiteSpace(c)));

removes all whitespace including unicode

Needs to be fixed here: https://github.com/openmod/openmod/blob/master/unturned/OpenMod.Unturned/OpenModUnturnedHost.cs#L179
