### ISSUE TITLE
Discord.Net.Webhook don't supported by OpenMod?

### ISSUE THREAD

**Issue by Senior-S** [openmod/openmod#166]
Hello, today i created a new plugin and the plugin use the library Discord.Net.Webhook, i installed my plugin (.dll) and when the plugin are loaded, i installed the library (openmod install Discord.Net.Webhook) later restarted the server (shutdown and re-open) and now the server give me the attached error, i trying with other libraries (Rest.Sharp) with the same process and openmod don't give any error, i think is a error with the library (Discord.Net.Webhook) but the question is Why?
[Server_OpenModOnly.log](https://github.com/openmod/openmod/files/5057788/Server_OpenModOnly.log)

**Comment by Trojaner** [comment]
Does this issue still persist?

**Comment by educatalan02** [comment]
A solution to this, would be creating your Library to do Webhooks

**Comment by sunnamed434** [comment]
The same problem for me. It is more a Mono problem rather than an OpenMod, it's time for DiscordWebhook.Mono project, [example](https://github.com/negrifelipe/DiscordMessenger)
