### ISSUE TITLE
List of Unturned Events and Wrappers

### ISSUE THREAD

**Issue by Trojaner** [openmod/openmod#169]
This is a list of Unturned specific events and wrappers that are going to be  added. Some of these events also exists as universal events. These events should be cancellable when possible.

# Players
- [x] UnturnedPlayerPerformingAidEvent 
- [x] UnturnedPlayerCraftEvent
- [x] UnturnedPlayerDamageEvent
- [x] UnturnedPlayerDeathEvent
- [x] UnturnedPlayerDeadEvent
- [x] UnturnedPlayerConnectEvent
- [x] UnturnedPlayerDisconnectEvent
- [x] UnturnedPlayerSpawnEvent
- [x] UnturnedPlayerTeleportEvent
- [x] UnturnedPlayerItemEquipEvent
- [x] UnturnedPlayerItemUnequipEvent
- [x] UnturnedPlayerThirstUpdateEvent
- [x] UnturnedPlayerHungerUpdateEvent
- [x] UnturnedPlayerInfectionUpdateEvent
- [x] UnturnedPlayerUpdateStanceEvent
- [x] UnturnedPlayerUpdateHealthEvent
- [x] UnturnedPlayerUpdateStatEvent
- [x] UnturnedPlayerUpdateExperienceEvent
- [ ] UnturnedPlayerInteractEvent
- [x] UnturnedPlayerEnterVehicleEvent
- [x] UnturnedPlayerExitVehicleEvent
- [ ] UnturnedPlayerUseItemEvent
- [x] UnturnedPlayerChatEvent
- [ ] UnturnedPlayerModifySignEvent
- [ ] UnturnedPlayerHarvestPlantEvent
- [x] UnturnedPlayerOpenStorageEvent
- [x] UnturnedPlayerCloseStorageEvent
- [ ] UnturnedPlayerOpenDoorEvent
- [ ] UnturnedPlayerCloseDoorEvent
- [x] UnturnedPlayerSalvageBarricadeEvent
- [x] UnturnedPlayerSalvageStructureEvent
- [x] UnturnedPlayerWearClothingEvent
- [x] UnturnedPlayerRespawnEvent
- [ ] UnturnedPlayerButtonClickedEvent
- [x] UnturnedPlayerPickupItemEvent
- [x] UnturnedPlayerDropItemEvent
- [ ] UnturnedPlayerGestureEvent
- [x] UnturnedPlayerBleedingStartEvent
- [x] UnturnedPlayerBleedingStopEvent
- [x] UnturnedPlayerBrokenStartEvent
- [x] UnturnedPlayerBrokenStopEvent
- [x] UnturnedPlayerInventoryAddItemEvent
- [x] UnturnedPlayerInventoryRemoveItemEvent
- [x] UnturnedPlayerInventoryResizeEvent
- [x] UnturnedPlayerInventoryUpdateEvent

# Zombies
- [x] UnturnedZombieSpawnEvent
- [x] UnturnedZombieDamageEvent
- [x] UnturnedZombieDeadEvent
- [x] UnturnedZombieAlertEvent

# Animals
- [x] UnturnedAnimalSpawnEvent
- [x] UnturnedAnimalDamageEvent
- [x] UnturnedAnimalDeadEvent
- [x] UnturnedAnimalFleeEvent
- [x] UnturnedAnimalAlertEvent

# Vehicles
- [x] UnturnedVehicleSpawnEvent
- [x] UnturnedVehicleDamageEvent
- [x] UnturnedVehicleExplodeEvent
- [ ] UnturnedItemSpawnEvent

# Environment
- [x] UnturnedNightEvent
- [x] UnturnedDayEvent
- [x] UnturnedFullMoonEvent
- [x] UnturnedWeatherChangeEvent
- ...

Please contribute to the list of events you would like to see wrapped by OpenMod. You can also add other kind of wrappers (e.g. around barricades/structures) or helper methods.

**Comment by Senior-S** [comment]
Events:
- UnturnedPlayerGestureEvent
- UnturnedPlayerOnDamageBarricadeRequested
- UnturnedPlayerOnBarricadeSpawned 
- UnturnedPlayerOnHarvestPlantRequested
- UnturnedPlayerOnModifySignRequested
- UnturnedPlayerOnSalvageBarricadeRequestd
- UnturnedPlayerOnChatted
- UnturnedPlayerOnButtonClicked
- UnturnedPlayerOnTakeItemRequested
- UnturnedPlayerOnClothesUpdated (new enum with the type of cloth like 0 = backpack or something like that)
Helpers:
- RaycastHelper(UnturnedUser, maxdistance, Raycast.PLAYER, Raycast.BARRICADE ...)

**Comment by DiFFoZ** [comment]
# Player events
- UnturnedPlayerStanceEvent
- UnturnedPlayerDropItemEvent
- UnturnedPlayerBleedingEvent
- UnturnedPlayerBrokenEvent
- UnturnedPlayerExperienceEvent
# Animal events
- UnturnedAnimalDamageEvent
- UnturnedAnimalDeadEvent
- UnturnedAnimalSpawnEvent
- UnturnedAnimalAliveEvent
# Zombie events
- UnturnedZombieDamageEvent
- UnturnedZombieDeadEvent
- UnturnedZombieAliveEvent

**Comment by rube200** [comment]
Events:
- [ ] BarricadeManager.askClaimBed
- [ ] BarricadeManager.tryGetBed
- [ ] BarricadeManager.tellTakeBarricade
- [ ] Carepackage.squishPlayersUnderBox //this event happens when Airdrop hit the ground and its before items get gerated
- [ ] InteractableBeacon.ManualOnDestroy
- [ ] typeof(Item).GetConstructor(...)
- [ ] PlayerAnimator.askGesture
- [ ] PlayerEquipment.sendUpdateQuality
- [ ] PlayerQuests.trackZombieKill //with this one u can get which player kill the zombie
- [ ] Provider.verifyNextPlayerInQueue
These are the main events that I use with harmony.
Probably some on this list will not be able to be used in OM.

**Comment by Pustalorc** [comment]
# Buildables

- OnBuildableDestroyed
- OnBuildablePlaced
- OnBuildableDamaged (post event)
- OnBuildableDisplaced

See [discord](https://discordapp.com/channels/666327627124047872/721920792740495461/744962589292757055) for reasoning for the first 2 events. Naming can be changed, and I believe these events could be implemented globally.

**Comment by IAmSilK** [comment]
Checking items off as they're added and tested. Checking does not mean that an exact equal event has been added, many of these have been changed to follow consistent naming schemes or are similar implementations to that requested.
