### ISSUE TITLE
Wrong base dir

### ISSUE THREAD

**Issue by rube200** [openmod/openmod#186]
OM folder is being created in the wrong path.

```bash
cd C:\Folder
C:\Unturned\Unturned.exe (..)
```
OM folder is being created at C:\Folder\Servers\(...)

**Comment by Trojaner** [comment]
Working directory is set here:
https://github.com/openmod/openmod/blob/master/unturned/OpenMod.Unturned.Module/OpenModUnturnedModule.cs#L33
https://github.com/openmod/openmod/blob/master/unturned/OpenMod.Unturned.Module.Dev/OpenModUnturnedModule.cs#L35
