### ISSUE TITLE
Chat color is wrong in Unturned

### ISSUE THREAD

**Issue by Trojaner** [openmod/openmod#201]
Output of /openmod command:
![image](https://user-images.githubusercontent.com/1809172/93001897-02f97580-f53b-11ea-9c22-8046a3ab1092.png)

It should be green instead.

**Comment by vnwatermelon** [comment]
I am pretty sure this is also the case with /p, I'll see if I can get a screenshot of it. I noticed it last night.

**Comment by Trojaner** [comment]
Issue is fixed and will be deployed on next release
