### ISSUE TITLE
First console input is always ignored

### ISSUE THREAD

**Issue by IAmSilK** [openmod/openmod#240]
To reproduce:
- Start OpenMod Unturned Server
- Wait for everything to load
- Type command and press enter
- Type another command and press enter - it will work now

Likely something to do with the switching in console inputs.
Not sure if this is exclusive to OpenMod.Unturned,

**Comment by Trojaner** [comment]
Issue is exclusive to OpenMod.Unturned

**Comment by Trojaner** [comment]
Can not reproduce on latest OpenMod 3
