### ISSUE TITLE
Basic Events

### ISSUE THREAD

**Issue by rube200** [openmod/openmod#25]
- [ ] On shutdown event
- [ ] Permission Group changes event
- [x] Plugin load event
- [x] Plugin unload event
- [x] User first connect event
- [x] User chat event

**Comment by Trojaner** [comment]
Shutdown event makes sense, but regarding save there is no such thing in OpenMod. I don't think plugins should depend on a save event but instead use their own save logic. 

What's the purpose of permission related events?

**Comment by rube200** [comment]
If a player is added to a group (for example)
So plugins could track it

**Comment by Trojaner** [comment]
Events for changes to player groups make sense

**Comment by Trojaner** [comment]
We can also add UserFirstJoinEvent. It can be called when user data is seeded which normally only happens on first join.

**Comment by rube200** [comment]
Probably an event for when the player dies

**Comment by Trojaner** [comment]
I will edit the first post add all missing events there
