### ISSUE TITLE
Console.BackgroundColor doesn't reset after ERR

### ISSUE THREAD

**Issue by D-AIRY** [openmod/openmod#252]
![Screenshot_2020-11-16 Siller LiveRP Unturned  #1  Панель](https://user-images.githubusercontent.com/20150321/99237410-78b6e180-2809-11eb-93db-cb5634eeab4e.png)

**Comment by Trojaner** [comment]
I can not reproduce this

**Comment by D-AIRY** [comment]
Are you using xterm-compatible terminal?

**Comment by Charterino** [comment]
This issue is probably related to your hosting provider

**Comment by D-AIRY** [comment]
Oh, it seems it uses Console.ResetColor(). I didn't know about that method. My bad
