### ISSUE TITLE
Event:Zombies killed by players 

### ISSUE THREAD

**Issue by y1meng** [openmod/openmod#253]
Why is there no event of killing zombies,Will it increase in the future?

**Thanks for your answer.**

**Comment by IAmSilK** [comment]
No player info exists at the method where zombies are damaged - `Zombie.askDamage`. This info is available before the zombie is damaged though. So I'll add on to this issue:

`UnturnedZombieDamagingEvent` should hook on to `DamageTool.damageZombieRequested` instead of patching `Zombie.askDamage`.

**Comment by y1meng** [comment]
> No player info exists at the method where zombies are damaged - `Zombie.askDamage`. This info is available before the zombie is damaged though. So I'll add on to this issue:
> 
> `UnturnedZombieDamagingEvent` should hook on to `DamageTool.damageZombieRequested` instead of patching `Zombie.askDamage`.

Is there a development plan?
