### ISSUE TITLE
IUserDataStore changes

### ISSUE THREAD

**Issue by rube200** [openmod/OpenMod#26]
IUserDataStore should have a new method:

```
async Task<UserData> GetUserDataAsync(string userId, string userNameOrId);
or
 async Task<UserData> GetOnlineUserDataAsync(string userId, string userNameOrId);
```

This makes it possible for plugins to get a player's data by name, so some plugins can be universal instead of just for a specific game

(I can do a pr if u want)
(and I just found out that I can access the data directly, but this should still be implemented)

**Comment by Trojaner** [comment]
I am against this, especially against userNameOrId.

I am planning to add a IUserManager.  The UserManager can be used to get online (and offline?) IUsers (by name or id).
You can then access the IUsers data.

**Comment by rube200** [comment]
This would help a lot to create universal plugins
