### ISSUE TITLE
why i cant  Resolve IOpenModPlugin in ContainerBuilderExtensions?

### ISSUE THREAD

**Issue by HanaForward** [openmod/openmod#263]
i am try to  context.Resolve<IOpenModPlugin>();  in ContainerBuilderExtensions
but Autofac cant find IOpenModPlugin.
it was iInjection  in  class PluginActivator :Line  135

**Comment by rube200** [comment]
You are suppose to resolve IOpenModPlugin.
You should use PluginActivator<PluginType>

**Comment by HanaForward** [comment]
In PluginActivator, it has been injected into containerBuilder，so i think it can Resolve<IOpenModPlugin>() in IPluginContainerConfigurator， IConfiguration and ILoggerFactory is OK, but just IOpenModPlugin is cant

**Comment by HanaForward** [comment]
......oh no ，I ordered wrong

**Comment by Trojaner** [comment]
IOpenModPlugin is only available in plugin scopes, it is not available in global scope. You can also not access it while the plugin container gets created.

**Comment by HanaForward** [comment]
I think IOpenModPlugin  has plugin info, It should be possible to get the plugin when it use ContainerConfigurator.
so if i ues it on ContainerConfigurator, autofac will tell me :  Circular component dependency detected.
How to track exceptions generated by services injected by plugins?

**Comment by HanaForward** [comment]
Now it seems that the only way is to pass plug assembly in ConfigureContainer

**Comment by HanaForward** [comment]
I created the OpenModAssembly interface，This issues is close,
Now I can know the source in IPluginContainerConfigurator
