### ISSUE TITLE
plugin dependency declaration

### ISSUE THREAD

**Issue by HanaForward** [openmod/openmod#271]
The Extensions Abstractions declares the plugin to be installed
openmod install OpenMod.Economy Will install OpenMod.Economy and OpenMod.Economy.Abstractions 
but when other plugins quote OpenMod.Economy.Abstractions , can openmod be installed OpenMod.Economy?

**Comment by Trojaner** [comment]
No. This is a wrong relationship. OpenMod.Economy.Abstractions works with any supported economy plugin, not just OpenMod.Economy. The relationship is OpenMod.Economy depends on OpenMod.Economy.Abstractions not the other way around.

**Comment by HanaForward** [comment]
Will ConfigureContainer  the same members be covered?
PlayerLibrary Register<ISqlSugarClient>(...)
Other plug too Register<ISqlSugarClient>(...)
Will ISqlSugarClient be overwritten ?
I ran into this problem
@Trojaner

**Comment by Trojaner** [comment]
You need to register ISqlSugarClient in the plugins scope using PluginContainerConfigurationEvent

**Comment by HanaForward** [comment]
A Register ISqlSugarClient in PluginContainerConfigurator
B Register ISqlSugarClient in PluginContainerConfigurator
when B invoke A Extensions Abstractions , the A ISqlSugarClient is From B , not is A ISqlSugarClient ;

**Comment by HanaForward** [comment]
https://github.com/HanaForward/PlayerLibrary
when i use  IPlayerLibraryProvider.FindPlayer(steamId), it will use invoker ISqlSugarClient  , but i want it use PlayerLibrary Register 
 ISqlSugarClient

**Comment by Trojaner** [comment]
This is normal and the expected behavior.

**Comment by Trojaner** [comment]
To fix this issue you can either create your service in the global scope and use IPluginAccessor<>.Instance.Lifetime to resolve the correct instance or declare something like IPlayerLibrarySqlSugarClientAccessor which does the same

**Comment by HanaForward** [comment]
ok thanks!

**Comment by Trojaner** [comment]
Here is an example on how you can do it:
```cs
[Service]
public interface IPlayerLibrarySqlSugarClientAccessor 
{
    public ISqlSugarClient SqlSugarClient { get; }
}

[ServiceImpementation]
public class PlayerLibrarySqlSugarClientAccessor : IPlayerLibrarySqlSugarClientAccessor 
{
    private IPluginAccessor<MyPlayerLibraryPlugin>> m_PluginAccessor;
    public PlayerLibrarySqlSugarClientAccessor(Lazy<IPluginAccessor<MyPlayerLibraryPlugin>> pluginAccessor)
    {
         m_PluginAccessor = pluginAccessor;
    }   

    public ISqlSugarClient SqlSugarClient 
    {
         get 
         {
              return m_PluginAccessor.Value.Instance.Lifetime.Resolve<ISqlSugarClient>();
         }
    }
}
```

**Comment by HanaForward** [comment]
https://github.com/HanaForward/PlayerLibrary/blob/master/PlayerLibrary/Provider/PlayerLibraryProvider.cs
@Trojaner 
Thanks your help.

**Comment by HanaForward** [comment]
i will updaye VehicleSQL for openmod
