### ISSUE TITLE
CommandBase permission

### ISSUE THREAD

**Issue by rube200** [openmod/openmod#28]
`private readonly string m_CommandPermission;`
Should be protected instead.

So the commands can know what your permission is.
Example:
`if (!await m_PermissionChecker.CheckPermissionAsync(Context.Actor, $"{m_CommandPermission}.can_do_to_other_player"))
{
//no permission
}
`

**Comment by Trojaner** [comment]
Command permissions are calculated via ICommandPermissionBuilder.GetPermission. CommandBase has a CheckPermissionAsync which checks for sub permissions, so you could just do CheckPermissionAsync("can_do_to_other_player").

**Comment by rube200** [comment]
Maybe a atribute with the subpermission and a shorts description for it

**Comment by Trojaner** [comment]
Yea, I was thinking the same
