### ISSUE TITLE
"Unable to match "openmod install OpenMod.Rocket.Unturned" with any built-in commands"

### ISSUE THREAD

**Issue by cherpak1** [openmod/openmod#310]
Installed openmod but had some troubles with command "openmod install OpenMod.Rocket.Unturned".
One dude told me to log into discord server but i was unable to find the link. Anyway, what to do with this?

Screenshot;
![image](https://user-images.githubusercontent.com/77220464/104341666-b59a0e80-5502-11eb-917c-4a30540a1a9e.png)

**Comment by cherpak1** [comment]
https://github.com/openmod/openmod/labels/area-Unturned https://github.com/openmod/openmod/labels/bug

**Comment by cherpak1** [comment]
label:bug

**Comment by Trojaner** [comment]
OpenMod is not installed correctly. Please install it manually by downloading the latest version from the Releases tab
