### ISSUE TITLE
UnturnedProfiler for OpenMod

### ISSUE THREAD

**Issue by nuage00** [openmod/openmod#314]
ImperialPlugins's UnturnedProfilier for RocketMod is good for developers and experienced server owners. But I can't find something like that for OpenMod. Maybe it can be done with a plugin or a configurable system working in OpenMod.

**Comment by Trojaner** [comment]
The way how the UnturnedProfiler works is bad. It patches all methods which results in a lot of overhead. I don't want to add something like that to OpenMod as it would affect performance too much. If we are going to add profiling for plugins to OpenMod it needs to be using mono's profiler APIs

**Comment by nuage00** [comment]
Oh Idk The Performance Side. But If I See That For A Plugin, It's Enough For Me. Also Sorry For The Wrong Title ^^
