### ISSUE TITLE
Libs and NuGet Parallel Download

### ISSUE THREAD

**Issue by rube200** [openmod/openmod#36]
Some libs like Harmony and Json are included on release file, they should be downloaded by nuget.
And talking about downloading stuff with nuget,
To speed up the time, transfers could be made in parallel (if possible)
ps: I tried to do it but they were duplicated

**Comment by Trojaner** [comment]
These libs can not be downloaded by nuget as they are needed by the module itself

**Comment by rube200** [comment]
oh, ok and about parallel?

**Comment by Trojaner** [comment]
It is likely possible but its not really important at this stage
