### ISSUE TITLE
logging.yaml overrides are not applied

### ISSUE THREAD

**Issue by Trojaner** [openmod/openmod#386]
For some reason overrides from logging.yaml are not longer applied since introducing YAML variables.
Results in lots of EF Core spam. Other options work fine.

**Comment by DiFFoZ** [comment]
https://github.com/openmod/openmod/blob/cfecf5d977651973589d8c284259770e0145a464/framework/OpenMod.Core/Configuration/YamlConfigurationProviderEx.cs#L44
Maybe adding `writer.Flush()` after write will fix it
