### ISSUE TITLE
Prefix/Suffix etc. from RocketMod is ignored after installing OpenMod 

### ISSUE THREAD

**Issue by Trojaner** [openmod/openmod#413]

**Comment by DiFFoZ** [comment]
@rube200 in [pr](https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/pull/15) says

> About prefixes and suffixes: i changed the event from Provider.onCheckValid to Provider.onCheckValidWithExplanation and some otimizations.

Because OpenMod listens Provider.onCheckValidWithExplanation, so that's why Provider.onCheckValid will not be called.

**Comment by Trojaner** [comment]
We should manually call onCheckValid then

**Comment by rube200** [comment]
yeh but if Nelson wants to keep old code compatibility, why do he do stuff like that? It should just be marked as obsolete but called in anyway since it does not affect the game at all.
Same happen with plugins that used the old damage event.
