### ISSUE TITLE
Cooldown loop

### ISSUE THREAD

**Issue by Teesxm** [openmod/openmod#434]
When a player is in two or more groups which have the same permission with different cool downs (using Rocket Permissions, specifically Advanced Perms), they get a bug which causes their cooldown for said permission to restart/loop infinitely.

Here’s a clip of the issue occurring:
https://cdn.discordapp.com/attachments/752620813915783201/818496750250754048/2021-03-08_15-51-08.mp4

Tested this with:
Donator group - `<Permission Cooldown="10">NewEssentials:commands.home</Permission>`

Default group - `<Permission Cooldown="0">NewEssentials:commands.home</Permission>`

**Comment by Trojaner** [comment]
Issue should be fixed with latest Advanced Permissions
