### ISSUE TITLE
Give all permissions to blue admin

### ISSUE THREAD

**Issue by DiFFoZ** [openmod/OpenMod#46]
Right now blue admins (Vanilla admin) can't execute commands

**Comment by DiFFoZ** [comment]
Still doesn't work. I'm investigate

**Comment by DiFFoZ** [comment]
https://github.com/openmod/OpenMod/blob/01ae359303e3ec39d021a5558eb05eb760826f70/unturned/OpenMod.Unturned/Permissions/UnturnedAdminPermissionCheckProvider.cs#L10
`actor is UnturnedUser user` always return false

**Comment by Trojaner** [comment]
Will check later
