### ISSUE TITLE
OpenMod server stuck on starting

### ISSUE THREAD

**Issue by frazzleman10** [openmod/openmod#462]
So i changed my unturned server over to OpenMod, and put the openmod.unturned folder into the modules folder and started the server, and it goes perfectly fine, then it gets so far and gets stuck on this
![image](https://user-images.githubusercontent.com/66959168/113679042-39553880-96b7-11eb-9068-9ca2f9a173a4.png) Does anyone know how to fix this?

**Comment by Trojaner** [comment]
Could be caused by plugins you are using

**Comment by Trojaner** [comment]
Is this still an issue?

**Comment by frazzleman10** [comment]
no
