### ISSUE TITLE
Is it possible to request to add user information to the zombie death event?

### ISSUE THREAD

**Issue by y1meng** [openmod/openmod#470]
![image](https://user-images.githubusercontent.com/45099938/114257865-58c0ce00-99f5-11eb-8650-33ace08e195a.png)

Just like the injury incident, **thank you very much to the OpenMod developers!!!**

**Comment by 01-Feli** [comment]
@y1meng if you mean the ELimb that was added yesterday. I think: https://github.com/openmod/openmod/commit/472e5a6697e5ba2973bfe931a2d784be4901b337

**Comment by 01-Feli** [comment]
You will have to wait until that change got release

**Comment by y1meng** [comment]
> You will have to wait until that change got release

Sorry, I did not understand what "ELimb" is, then I will wait for the release to determine if it is what I need

**Comment by Trojaner** [comment]
You can use IUserManager or IUnturnedUserDirectory to get UnturnedUser from UnturnedPlayer

**Comment by y1meng** [comment]
> You can use IUserManager or IUnturnedUserDirectory to get UnturnedUser from UnturnedPlayer

![image](https://user-images.githubusercontent.com/45099938/114268723-36e73b80-9a35-11eb-81b0-a4baa7fb2479.png)
So what information should I use to match this killer?

**Comment by Trojaner** [comment]
GetUser(UnturnedPlayer.Player)

**Comment by y1meng** [comment]
> GetUser(UnturnedPlayer.Player)

Sorry, I don't understand at all where UnturnedPlayer.Player should be obtained from...

**Comment by 01-Feli** [comment]
@y1meng you can get it from the user that is on the event https://i.imgur.com/dxBEyAj.png
