### ISSUE TITLE
UnityTransform: '?.' bypasses the unity lifetime check

### ISSUE THREAD

**Issue by DiFFoZ** [openmod/openmod#495]
https://github.com/JetBrains/resharper-unity/wiki/Possible-unintended-bypass-of-lifetime-check-of-underlying-Unity-engine-object

All possible bypasses:

https://github.com/openmod/openmod/blob/bbcc46576a14d2a2db886fa44b512e12ac10b948/unityengine/OpenMod.UnityEngine/Transforms/UnityTransform.cs#L56

https://github.com/openmod/openmod/blob/bbcc46576a14d2a2db886fa44b512e12ac10b948/unityengine/OpenMod.UnityEngine/Transforms/UnityTransform.cs#L58

https://github.com/openmod/openmod/blob/bbcc46576a14d2a2db886fa44b512e12ac10b948/unityengine/OpenMod.UnityEngine/Transforms/UnityTransform.cs#L105

**Comment by Trojaner** [comment]
We should use Microsoft.Unity.Analyzers to get warnings about such cases
