### ISSUE TITLE
A large openmod.users.yaml increases ping

### ISSUE THREAD

**Issue by muertoof** [openmod/openmod#502]
I have a pretty big user file, which consists of 3.2k users (35k lines, 878KB).

This file to blame for the increase in ping when connecting / disconnecting players to the server. I tested this on a server without plugins and the problem was confirmed.

Also, interacting with UserData in a big file takes a long time. For example: checking if a player has a certain column in the data takes about 5-6 seconds.

**Comment by 01-Feli** [comment]
> 
> 
> I have a pretty big user file, which consists of 3.2k users (35k lines, 878KB).
> 
> This file to blame for the increase in ping when connecting / disconnecting players to the server. I tested this on a server without plugins and the problem was confirmed.
> 
> Also, interacting with UserData in a big file takes a long time. For example: checking if a player has a certain column in the data takes about 5-6 seconds.

I think you should provide your host features and the average of connected players, i think that information will be helpfull to someone help you

**Comment by 01-Feli** [comment]
if you want send me that file and i will try on my localhost

**Comment by Johnanater** [comment]
A workaround for this seems to be running the code in the events `OnPlayerConnected`, `OnPlayerDisconnected`, `OnRejectingPlayer`, and `OnPendingPlayerConnecting` in UnturnedUserProvider on another thread with `AsyncHelper.Schedule()`.

**Comment by CyberAndrii** [comment]
The issue is caused by YAML serialization here https://github.com/openmod/openmod/blob/884ea142b9447d4c0faf5ad3973c6c8765a59d88/framework/OpenMod.Core/Persistence/YamlDataStore.cs#L163
With 5000 users it serializes in 600ish milliseconds.

With a lot of players, it will be better to save to a database than to file.
