### ISSUE TITLE
CommandStore not providing all commands sources

### ISSUE THREAD

**Issue by rube200** [openmod/OpenMod#51]
https://github.com/openmod/OpenMod/blob/e4a1e5eb3666ac844e6c0c75a9ff46d66ad9b3e9/framework/OpenMod.Core/CommandStore.cs#L21-L37

The class `CommandStore` creates a `CommandSources` on contructor, the problem is that plugins have not been loaded yet, so plugins commands are not included.

**Comment by rube200** [comment]
A Debug
[ConsoleDebug.log](https://github.com/openmod/OpenMod/files/4810619/ConsoleDebug.log)

**Comment by Kr4ken-9** [comment]
I have experienced this bug too. I did some research and the commands are registered successfully: https://github.com/openmod/OpenMod/blob/master/framework/OpenMod.Core/Commands/OpenModComponentCommandSource.cs#L30
(Both Methods and Types are found successfully and Commands.Add is called).

This is the only thing I found out before I got busy.

**Comment by rube200** [comment]
I know that, and i know the cause, i just dont know how to solve it without messing the code.
As I said before the constructor of `CommandStore` is called before all commands are registered, so when u execute a command is registered but not contained on commands list

**Comment by Trojaner** [comment]
We could create CommandSource instances when getting the commands instead of in tine constructor, but this could negatively impact performance as the activating process is slow. It is weird that the constructor is called so early.

**Comment by rube200** [comment]
Why we do not create a dirty buffer? Or something similar.
I commandsSources change it would detect and create a new mapping

**Comment by Trojaner** [comment]
The IOptionsMonitor interface makes it possible to listen for changes, but I do not know how to notify about changes yet.
