### ISSUE TITLE
Player death causes large ping spikes when having a large openmod.users.yaml

### ISSUE THREAD

**Issue by DronXa** [openmod/openmod#537]
Player death causes large ping spikes when having a large openmod.users file. This has been tested with a 650KB user file. After deleting the file the lag spikes are resolved.  The only openmod plugins that are used is Newessentials, OpenDeathMessages and ChatAnnoyer. 

Any type of player death causes the ping spikes, even suicides.

**Comment by DronXa** [comment]
Newessentials saves playerdeath in openmod.users file, this issue might be related to player data storage in openmod.users.

**Comment by Trojaner** [comment]
Yeah, we should fix this at the root by figuring out why deserialization is so slow. Its prob. because we chose yaml over json

**Comment by rube200** [comment]
O^2 loop
https://github.com/openmod/openmod/blob/1f48d4ebc560529b53586f072649cf494c565373/framework/OpenMod.Core/Users/UserDataStore.cs#L209-L215

Another O loop
https://github.com/openmod/openmod/blob/53c2ef9c8cb27a764f177a9700e8521089cc0dd1/framework/OpenMod.Core/Persistence/YamlDataStore.cs#L163
(O^3)

ComputeHash
https://github.com/openmod/openmod/blob/53c2ef9c8cb27a764f177a9700e8521089cc0dd1/framework/OpenMod.Core/Persistence/YamlDataStore.cs#L172

Another ComputeHash
https://github.com/openmod/openmod/blob/53c2ef9c8cb27a764f177a9700e8521089cc0dd1/framework/OpenMod.Core/Persistence/YamlDataStore.cs#L182

FileWrite that can be slow in some disks https://github.com/openmod/openmod/blob/53c2ef9c8cb27a764f177a9700e8521089cc0dd1/framework/OpenMod.Core/Persistence/YamlDataStore.cs#L203

**Comment by rube200** [comment]
Sugestion: make `YamlDataStore.SaveAsync` run in another thread since it already uses locks

**Comment by IAmSilK** [comment]
Thread-locking `lock`s should not be used. Should change to using Nito.AsyncEx's `AsyncLock`s.

File.WriteAllBytes will lock the thread as well, so this should transfer to another thread as well.

**Comment by Trojaner** [comment]
File.WriteAllBytes is acceptable in this case, it shouldn't block for too long in the majority of cases. Unfortunately the built-in async version of it was not available last time I checked, but we could write our own async version with TaskCompletionSource and QueueUserWorkItem

**Comment by rube200** [comment]
No updates on this, and already have a pr associated
