### ISSUE TITLE
UnturnedCommand has the OpenModInternal attribute

### ISSUE THREAD

**Issue by kotyk7** [openmod/openmod#541]
Isn't that a bug? 

Added in commit e01c7a865739d5e403424316464a32239f70b565
https://github.com/openmod/openmod/blob/e01c7a865739d5e403424316464a32239f70b565/unturned/OpenMod.Unturned/Commands/UnturnedCommand.cs

**Comment by IAmSilK** [comment]
To add on, these should be reviewed:
- https://github.com/openmod/openmod/blob/e01c7a865739d5e403424316464a32239f70b565/framework/OpenMod.API/Plugins/IPluginActivator.cs
- https://github.com/openmod/openmod/blob/e01c7a865739d5e403424316464a32239f70b565/framework/OpenMod.API/Plugins/IPluginAssemblyStore.cs

**Comment by Trojaner** [comment]
The one for UnturnedCommand should be removed, but the other ones should only be used by plugin loaders and should stay.

**Comment by IAmSilK** [comment]
Some plugin loaders are still not internal.

Also, `IPluginActivator` is used by any plugin that wishes to enumerate loaded plugins. It has many external purposes other than plugin loaders.
