### ISSUE TITLE
TrunkEvent

### ISSUE THREAD

**Issue by Nacho-Neko** [openmod/openmod#545]
UnturnedPlayerOpenedTrunkEvent
UnturnedPlayerCloseTrunk

**Comment by 01-Feli** [comment]
@Nacho-Neko you can create this event by patching closeTrunk and openTrunk from PlayerInventory

**Comment by Nacho-Neko** [comment]
I have done it.
UnturnedPlayerOpenedStorageEvent  need enhancement 
```
        [HarmonyPrefix]
        [HarmonyPatch("openStorage")]
        public static bool openStorage(PlayerInventory __instance, InteractableStorage newStorage)
        {
            if (__instance.isStoring)
            {
                __instance.closeStorage();
            }
            newStorage.isOpen = true;
            newStorage.opener = __instance.player;
            __instance.isStoring = true;
            __instance.isStorageTrunk = false;
            __instance.storage = newStorage;
            OpenStorageEvent?.Invoke(__instance, newStorage);
            return false;
        }
```

We can modify the opened content

**Comment by Nacho-Neko** [comment]
@01-Feli  @DiFFoZ

**Comment by Nacho-Neko** [comment]
when closeStorage we need  modify  the  save content

**Comment by Nacho-Neko** [comment]
UnturnedPlayerOpenedTrunkEvent be consistent

**Comment by 01-Feli** [comment]
> 
> 
> I have done it.
> UnturnedPlayerOpenedStorageEvent need enhancement
> 
> ```
>         [HarmonyPrefix]
>         [HarmonyPatch("openStorage")]
>         public static bool openStorage(PlayerInventory __instance, InteractableStorage newStorage)
>         {
>             if (__instance.isStoring)
>             {
>                 __instance.closeStorage();
>             }
>             newStorage.isOpen = true;
>             newStorage.opener = __instance.player;
>             __instance.isStoring = true;
>             __instance.isStorageTrunk = false;
>             __instance.storage = newStorage;
>             AsyncResut<bool> OpenResult = new AsyncResut<bool>();
>             OpenResult.Result = true;
>             Task OpenStorageTask = OpenStorageEvent?.Invoke(__instance, newStorage, ref AsyncResut<bool> OpenResult);
>             AsyncHelper.Schedule("openStorage", async () =>
>             {
>                 Task.WaitAll(OpenStorageTask);
>                 if (OpenResult.Result)
>                 {
>                     __instance.updateItems(PlayerInventory.STORAGE, newStorage.items);
>                     __instance.sendStorage();
>                 }
>             });
>             return false;
>         }
> ```
> 
> We can modify the opened content

There is no needs to replace the method code with harmony, just create a postfix patch for PlayerInventory.openStorage and then you can get the storage by doing

```
var storage = @event.Player.Player.inventory.items[PlayerInventory.STORAGE]
```

**Comment by 01-Feli** [comment]
and also this will also work in the case that the player opens a locker so for the trunk you need to patch the method that is called openTrunk, that is only called when the player will open a trunk storage

**Comment by Nacho-Neko** [comment]
what is postfix patch ?

**Comment by 01-Feli** [comment]
I dont catch what you mean

**Comment by Nacho-Neko** [comment]
look like save storage items in mysql

**Comment by rube200** [comment]
Any update on this @Nacho-Neko
