### ISSUE TITLE
IConfiguration.Bind() Don't working.

### ISSUE THREAD

**Issue by Senior-S** [openmod/openmod#549]
I was trying to use IConfiguration.Bind() in 2 different ways and it are don't working.

Code that I tried:
`m_Configuration.GetSection("configuration").Bind("test");`

`var conf = new Config();
m_Configuration.GetSection("configuration").Bind("test");`
Config: https://pastebin.com/hxTe1ydp

**Comment by Trojaner** [comment]
m_Configuration.GetSection("configuration").Bind(conf);

**Comment by Senior-S** [comment]
Still don't work.

**Comment by rube200** [comment]
I used it a while a go and it was working.
are u doing something wrong?

**Comment by Senior-S** [comment]
I was testing with a new openmod-unturned plugin and it still don't work, I tried with a white config file, adding manually the first section like
`configuration:`
And it still don't work.

**Comment by IAmSilK** [comment]
I have used Bind and had it work in the past, so it may either be your implementation that is incorrect or Mcirosoft's package possibly is having troubles on your OS.

But there is the `PluginConfigurationChangedEvent` which is another way to get the functionality you can get from the `Bind` method.

Take a look at my implementation [here.](https://github.com/SilKsPlugins/SilK.Unturned.Extras/blob/main/SilK.Unturned.Extras/Configuration/ConfigurationParser.cs)

You can also simply use my `SilK.Unturned.Extras` package from NuGet, but it contains more than just this configuration parser.

**Comment by aviadmini** [comment]
You should use `PluginConfigurationChangedEvent`. Believe me it will save you from a lot of butthurt
