### ISSUE TITLE
UnturnedZombieDyingEvent  There is a bug

### ISSUE THREAD

**Issue by y1meng** [openmod/openmod#559]
**Steps to reproduce:** 
Attacking zombies after using item ID 1194 will frequently trigger this event, but in fact the zombies did not die

**Comment by Trojaner** [comment]
Are you sure this is not an Unturned bug?

**Comment by y1meng** [comment]
Sorry, I don’t know how to provide a more detailed explanation, but as far as I know, RocketMod kills the zombie incident without such a problem, so I tend to be a bug in OpenMod

**Comment by y1meng** [comment]
![image](https://user-images.githubusercontent.com/45099938/129223461-1ababd57-13f6-4564-b90d-f942f4f7083d.png)
![image](https://user-images.githubusercontent.com/45099938/129223688-eb93e746-0cbc-4e62-8525-8cae1ff597ea.png)


The same id is the same zombie that is attacking, and I found that the more the zombie’s blood volume increases, the more likely this bug will occur.

**Comment by y1meng** [comment]
![image](https://user-images.githubusercontent.com/45099938/129291675-adbbdafe-3e45-4898-9c0a-4c08209bb8d8.png)

I don't understand what this time represents, is there a continuous damage weapon?

**Hope there are OpenMod developers to save me...**

**Comment by y1meng** [comment]
In addition, according to my players' feedback, if you use the left mouse button of the dagger to kill the zombie, the death event will not be triggered, and you can only use the right mouse button to hit...

Sorry for posting so many messages, hope the above clues can help developers locate the problem

**Comment by rube200** [comment]
Not sure about that issue but by your screenshot that event have a problem related to damage.

totalDamage = damage * times
...
damage = totalDamage

**Comment by y1meng** [comment]
I personally think this is a serious bug because it hinders the production of OpenMod basic plug-ins

> Not sure about that issue but by your screenshot that event have a problem related to damage.
> 
> totalDamage = damage * times
> ...
> damage = totalDamage

Will there be developers to verify this issue?

I personally think this is a serious bug because it hinders the production of OpenMod basic plug-ins

**Comment by aviadmini** [comment]
there's some inconsistency I see:

to calculate damage you're taking both `parameters.damage` and `parameters.times`

but after event is finished you only assign `parameters.damage`, but not `parameters.times`

This definitely causes inconsistent values when `parameters.times` is not equal to `1`
