### ISSUE TITLE
Give player experience

### ISSUE THREAD

**Issue by sergioliveira07** [openmod/openmod#561]
Is there any API method to give a player experience points? Or check is skills and all? Can't find any.

**Comment by 01-Feli** [comment]
> 
> 
> Is there any API method to give a player experience points? Or check is skills and all? Can't find any.

If i am correctly there is a method called AskAward on the PlayerSkill class

**Comment by sergioliveira07** [comment]
Yeah, but how to get a PlayerSkill from a name?!

**Comment by Senior-S** [comment]
> Yeah, but how to get a PlayerSkill from a name?!

Just use `PlayerTool.getPlayer(string name)`

**Comment by sergioliveira07** [comment]
Oh nice, thanks! But thats SDG Api, is there an OpenMod specific?

**Comment by 01-Feli** [comment]
yes. You can get the unturnedUser with the UserManager

Then you can access SDG.Player by doing unturnedUser.Player.Player

**Comment by 01-Feli** [comment]
You can use this method https://github.com/openmod/openmod/blob/ae85f43bda85cfeb4249f8d8e0b4344f86cd93e1/framework/OpenMod.API/Users/IUserManager.cs#L34 then cast the UnturnedUser for the IUser

**Comment by sergioliveira07** [comment]
`    [Command("experience")]
    [CommandAlias("exp")]
    [CommandAlias("xp")]
    [CommandDescription("Gives you a specific amount of experience")]
    [CommandSyntax("<amount>")]
    public class ExperienceCommand : UnturnedCommand
    {
        private readonly IUserManager UserManager;

        public ExperienceCommand(IServiceProvider serviceProvider, IUserManager userManager) : base(serviceProvider)
        {
            UserManager = userManager;
        }

        protected override async UniTask OnExecuteAsync()
        {
            //if (PlayerTool.getPlayer(Context.Actor.FullActorName) is Player player)
            if (await UserManager.FindUserAsync(KnownActorTypes.Player, Context.Actor.Id, UserSearchMode.FindById) is UnturnedPlayer player)
            {
                var amount = await Context.Parameters.GetAsync<uint>(0);

                player.Player.skills.askAward(amount);

                await Context.Actor.PrintMessageAsync($"You were given {amount} experience points.");

                return;
            }

            throw new UserFriendlyException("Something went wrong!");
        }
    }`

like this=

**Comment by 01-Feli** [comment]
No dont do that

**Comment by 01-Feli** [comment]
If you are going to get the user from the actor you can simply do 

If(Context.Actor is UnturnedUser unturnedUser){
// code
}

**Comment by 01-Feli** [comment]
Also i ll recommend you to check the args lenght before getting the ammoun of experience and also to check if it is a number because that the arg 0 can be null if no arguments were provided.
You can do 
```chsarp
Context.Parameters.TryGet<uint>(0, out var amount)
```
And it wil return true if the argument could be parsed and false if the argument couldnt be parsed

**Comment by sergioliveira07** [comment]
`protected override async UniTask OnExecuteAsync()
        {
            if (Context.Actor is UnturnedUser user && Context.Parameters.TryGet<uint>(0, out var amount))
            {
                user.Player.Player.skills.askAward(amount);

                await Context.Actor.PrintMessageAsync($"You were given {amount} experience points.");

                return;
            }

            throw new CommandWrongUsageException(Context);
        }`

So, this?!

**Comment by sergioliveira07** [comment]
Already tried on server , and worked, thanks !! @01-Feli @Senior-S
