### ISSUE TITLE
Send message to player without server icon

### ISSUE THREAD

**Issue by sergioliveira07** [openmod/openmod#563]
Is there a way to send a message to player without showing server icon?

Would also be nice if some one can tell me all ways to send a message.

**Comment by 01-Feli** [comment]
user.PrintMessageASync("My message");

**Comment by sergioliveira07** [comment]
`            await player.PrintMessageAsync(StringLocalizer.GetString("commands:request_sent", new { User = requestTo }));
            await requestTo.PrintMessageAsync(StringLocalizer.GetString("commands:request_sent_1", new { User = player }), System.Drawing.Color.Yellow, true, @"https://i.imgur.com/ETG0xud.png");
`

The first one, what u recommended and what i was using, show the server icon.
To hide it, i used a custom image, wich is full transparent, so no icon is shown.

A good thing would also be to get the steam player image url

**Comment by CyberAndrii** [comment]
Does it work if you pass an empty string instead of url?

**Comment by sergioliveira07** [comment]
> Does it work if you pass an empty string instead of url?

Yes, it does. Didn't think of it, nice.
