### ISSUE TITLE
How to get the player equiped item

### ISSUE THREAD

**Issue by sergioliveira07** [openmod/openmod#564]
I need to know an player equiped item.

I'm making a plugin and i need to know what weapon the player was using when killing other player, the event `UnturnedPlayerDeathEvent` does not return the weapon, so i'm assuming i'll have to use the equiped one.

Right now i found this:
`Player.Player.equipment.itemID`
Does this return the equiped Item?  Player is UnturnedPlayer.

And then i need to get the UnturnedItem to get the item name, but i don't find any method to do so.

**Comment by 01-Feli** [comment]
you can get the name form the item asset and if i remember correctly you can get if from 
```
Player.Player.equipment.asset.name
```

**Comment by sergioliveira07** [comment]
It works, but still, isn't there a `UnternedUserManager` or something to get items info?!
