### ISSUE TITLE
Styles in translations.yaml files

### ISSUE THREAD

**Issue by TeemoCell** [openmod/openmod#567]
OpenMod counts the style tag as normal letters in chat. Which means that the chat then starts in a new line if you have too many style tags. 

![image](https://user-images.githubusercontent.com/11705513/131229004-dccd1bf0-3b5a-4b46-8948-c13f2450cad1.png)
```yaml
cooldown: "<color=orange>Kit <color=yellow>{Kit.Name} (<size=12><color=yellow>{Cooldown:0} s</color></size>)</color> in cooldown.</color>"
```

**Comment by Trojaner** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2143
