### ISSUE TITLE
Unturned Command

### ISSUE THREAD

**Issue by TeemoCell** [openmod/openmod#580]
How can i set commands like "/day" in OpenMod?

**Comment by IAmSilK** [comment]
What do you mean by set commands?

**Comment by Nonanti** [comment]
You use Chatmanager.

example;
                ChatManager.instance.askChat(player.CSteamID, (byte)EChatMode.GLOBAL, "/day");

**Comment by 01-Feli** [comment]
🤦‍♂️

**Comment by rube200** [comment]
![image](https://user-images.githubusercontent.com/20555316/143437084-2ec3af1c-47e9-403c-8a72-25ec217de183.png)

**Comment by cemahseri** [comment]
![big_1496148706_image](https://user-images.githubusercontent.com/20908430/143439981-2d06f115-bb44-49eb-9795-4115df0f1676.jpg)

**Comment by TeemoCell** [comment]
I don't even know what I wanted myself anymore.

**Comment by Trojaner** [comment]
Fyi: the responses were to "Nonaniti"'s proposed solution, who has deleted his answer. 
This is not about you @TeemoCell. I have deleted the other replies as Nonaniti has deleted his post.
