### ISSUE TITLE
Server console freeze

### ISSUE THREAD

**Issue by TeemoCell** [openmod/openmod#581]
Server command freeze and server don't show the correct online status, ram or CPU usage. All servers without OpenMod are working fine.
![image](https://user-images.githubusercontent.com/11705513/136013580-f8c9e1aa-747b-404c-a8ce-c289c1a0d51a.png)

**Comment by 01-Feli** [comment]
what command are you trying to use?

**Comment by TeemoCell** [comment]
None. It's freeze right after server startup.

**Comment by TeemoCell** [comment]
-_-
