### ISSUE TITLE
YAML Role File

### ISSUE THREAD

**Issue by IISBNMII** [openmod/openmod#582]
Bought a ModernHosting Unturned server with plugins through OpenMod, cannot find the YAML Role file, either deleted or I'm just blind. How would I go around finding and/or creating one? Already tried to create one and didn't work.

**Comment by 01-Feli** [comment]
Provide your logs please

**Comment by 01-Feli** [comment]
YourServerId/OpenMod

**Comment by 01-Feli** [comment]
and inside the openmod folder you will see the logs one

**Comment by 01-Feli** [comment]
The folder is located at Servers

**Comment by IISBNMII** [comment]
-_- Found it, I was being an idiot, thanks!

**Comment by 01-Feli** [comment]
you can close the issue now as you found what you were looking for
