### ISSUE TITLE
Rcon commands not executing with rocketmod

### ISSUE THREAD

**Issue by ghost** [openmod/openmod#621]
I have an Unturned server that requires OpenMod to communicate with the game host's web chat interface.  I've setup rcon through rocketmod(supposed to override the OM settings).  I can connect, but practically everything comes back as "Command was not found:".
![Screenshot_20220725_173022](https://user-images.githubusercontent.com/103531662/180878812-c8055b69-14f6-438b-90da-983bebda50ec.png)

OpenMod logs that I am root, and the commands are being executed.
![Screenshot_20220725_173500](https://user-images.githubusercontent.com/103531662/180879271-1b8ab151-01a7-46a5-91d0-181002e0a267.png)

**Comment by TeemoCell** [comment]
Reported that already few months ago in the OpenMod discord but no one cares.
