### ISSUE TITLE
“UnturnedZombieDyingEvent” event trigger repeat

### ISSUE THREAD

**Issue by y1meng** [openmod/openmod#623]
If the zombie is killed by a shotgun, the death event will be triggered multiple times, such as item Id: 112

**Comment by y1meng** [comment]
`      public async Task HandleEventAsync(object sender, UnturnedZombieDyingEvent @event) {
            if (@event.Zombie.Zombie.isDead)
                await UniTask.SwitchToThreadPool();
     }
`

I found that the shotgun fires four bullets, and when the last three bullets trigger the event, the zombie is already dead,I don't know if this is a bug, but it seems to be working fine so far.

**Comment by rube200** [comment]
It need to checked and and fixed

**Comment by rube200** [comment]
After some analyze bug seems to be unturned side, lets wait for issue response before do any changes.

**Comment by rube200** [comment]
Issue should be fixed by unturned v3.22.15.0
