### ISSUE TITLE
Potential Bug on Ubuntu

### ISSUE THREAD

**Issue by EternalFG** [openmod/openmod#632]
When Im trying to use Events/Services occurs weird errors which is absolutely not related to what I do, but this is all working on Windows OS fine, but it wont work on Ubuntu 20.04.04 LTS

I pinned more information below (screenshots and link to exception in Pastebin also).
[Exception](https://pastebin.com/wbmSwPJg)
![image](https://user-images.githubusercontent.com/72083320/188282992-a635ffd0-484a-4653-8deb-3611e73e14f2.png)
Here is a config if it is required
![image](https://user-images.githubusercontent.com/72083320/188283023-a3a3628d-a8c0-4e13-af87-fb7f6ba8c251.png)
initial launch
![image](https://user-images.githubusercontent.com/72083320/188283052-2caf2136-ea9d-4b67-9cca-31853fcf5725.png)

**Comment by negrifelipe** [comment]
Hi, are you sure that you added the config.yaml as an embeded resource?

**Comment by EternalFG** [comment]
Yes

**Comment by EternalFG** [comment]
> Hi, are you sure that you added the config.yaml as an embeded resource?

Yes

**Comment by Trojaner** [comment]
Closing as it cannot be reproduced
