### ISSUE TITLE
Reloading causes RocketMod commands to use RocketMod permissions

### ISSUE THREAD

**Issue by Hydriuk** [openmod/openmod#647]
Configuration : 

_openmod.unturned.yaml_
```yaml
rocketmodIntegration:
  permissionSystem: OpenMod 
```

_openmod.users.yaml_
```yaml
- id:
  ...
  permissions: 
  - '*'
  roles:
  ...
```

Before reloading : 
**Rocket and OpenMod both use OpenMod's permissions** : 

- Running Openmod command with OpenMod Permission succeeds
- Running RocketMod command with OpenMod Permission succeeds
- Running OpenMod command without OpenMod Permission fails
- Running RocketMod command without OpenMod Permission fails

- /p returns OpenMod's permissions

After reloading : 
**RocketMod now uses RocketMod's permissions** : 

- Running Openmod command with OpenMod Permission succeeds
- **Running RocketMod command with OpenMod Permission fails**
- Running OpenMod command without OpenMod Permission fails
- **Running RocketMod command without OpenMod Permission suceeds if player has RocketMod permission**

- /p returns RocketMod's permissions

**Comment by DiFFoZ** [comment]
There's a problem is that OpenMod host initialized before subscribing to the events.
https://github.com/openmod/openmod/blob/9ea0225f9f36332bbd8be5ffd6d40dfcfdd9e7a3/framework/OpenMod.Runtime/OpenModHostedService.cs#L64-L69

**Comment by negrifelipe** [comment]
Has anyone ever tried to initialize openmod after subscribing to the events or any other way to get it to work?

**Comment by DiFFoZ** [comment]
IIRC we cannot subscribe to events while host is not initialized, see #700

**Comment by rube200** [comment]
What about creating a exception for those cases (#700 )
