### ISSUE TITLE
When there is a Beacon, UnturnedZombieDyingEvent has a chance to be falsely reported

### ISSUE THREAD

**Issue by y1meng** [openmod/openmod#660]
**Phenomenon:**
When there is a beacon, at certain times (related to the damage value), the zombie will be triggered twice "UnturnedZombieDyingEvent" event.

**My Investigation：**
Check the openmod source code to know that the event comes from DamageTool.damageZombieRequested, Then I checked the source code of [Unturned](https://github.com/Unturned-Datamining/Unturned-Datamining),I found that after damageZombieRequested is triggered, the damage value is also calculated,Eventually I found this verdict:
![image](https://user-images.githubusercontent.com/45099938/221411448-fc43d768-6fe1-4363-b491-2250d80f44dc.png),It seems that openmod also adds this judgment to be consistent with the game, but the zombieRegion field is inaccessible, and I cannot verify it

I don't speak English, if it is not clear, I will try to add, thank you

**Comment by y1meng** [comment]
In addition, the value of times has also been changed according to the configuration file, which has nothing to do with the question I raised, but I guess similar problems will occur if the server modifies the configuration

![image](https://user-images.githubusercontent.com/45099938/221411876-d844a90f-b832-4065-ade4-0d6a7397003b.png)

**Comment by rube200** [comment]
@IAmSilK can you fix this? i currently dont have any .net installed.
From the first image seems like we need to update our damage calculation code.
https://github.com/openmod/openmod/blob/1d5dabcb23f2a15e137c0f4175d885f383dfa2b2/unturned/OpenMod.Unturned/Zombies/Events/ZombieEventsListener.cs#L81-L83

For the second image it can be ignored since it basic math. (all values are multiplying)

**Comment by y1meng** [comment]
> For the second image it can be ignored since it basic math. (all values are multiplying)

why? i don't understand.

I have tested that if the configuration is modified to be greater than 1, the event will not be triggered (because the zombie will die early).

less than 1, and the event will be triggered in advance.

**Comment by rube200** [comment]
yeh, sorry you are right but that needs to be in a temp value just for check if zombie will die, it can not be pass in event
