### ISSUE TITLE
No IOpenModPlugin implementation found in assembly

### ISSUE THREAD

**Issue by Bermingen** [openmod/openmod#661]
Logs says me that, my plugin doesn't has a `IOpenModPlugin` implementation, but, honestly, its just unable to get the access to the signature i.e its unable to resolve LiteDB.dll as I guess.

[OpenMod.Core.Plugins.PluginAssemblyStore] No IOpenModPlugin implementation found in assembly: UnturnedGuard.OpenMod-73c45b, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null; skipping loading of this assembly as plugin

```cs
using OpenMod.Core.Plugins;
[assembly: PluginMetadata("UnturnedGuard")]
namespace UnturnedGuard.OpenMod;
public class UnturnedGuardPlugin : OpenModUniversalPlugin, IOpenModPlugin
{
    private readonly ILiteDatabase _liteDatabase;
    public UnturnedGuardPlugin(
        ILiteDatabase liteDatabase,
        IServiceProvider serviceProvider) : base(serviceProvider)
    {
        _liteDatabase = liteDatabase;
    }
    protected override Task OnUnloadAsync()
    {
        _liteDatabase.Dispose();
        return Task.CompletedTask;
    }
}
```

* After adding the LiteDB.dll into the plugins dir everything goes fine.

It's kind of weird a bit, I was a little confused at first, would be great to give more information in logs, just in case.

**Comment by CyberAndrii** [comment]
That's because `typeof(IOpenModPlugin).IsAssignableFrom(type)` return false when a dependency assembly is missing. AFAIK that only happens on Mono, and on other runtimes it will throw an exception instead. In fact, we've had this issue in the past with module loading and I think it's worth adding a better error message here or use [the fix](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2338#issuecomment-765089366) Trojaner found back then.

**Comment by rube200** [comment]
Hello @Bermingen i just patched om in this brench [general_fixes](https://github.com/openmod/openmod/tree/general_fixes). can you please test and report if it is working now? (correct output error)

**Comment by Bermingen** [comment]
Hi @rube200, I've got time to test it now, its works like a charm, thank you so much

```
ERR][SDG.Unturned] Could not find dependency: LiteDB, Version=5.0.15.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27
```

**Comment by rube200** [comment]
Okay soon i will make a Pr

**Comment by HathHub** [comment]
Reopening this as It won't work properly still

```
[2023-11-02 17:05:35 DBG][NuGet] Failed to resolve ShimmyMySherbet.MySQL.EF, Version=1.8.9.0, Culture=neutral, PublicKeyToken=null
[2023-11-02 17:05:35 DBG][NuGet] Failed to resolve ShimmyMySherbet.DiscordWebhooks, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
```

unless I add both dlls to plugin directory

**Comment by negrifelipe** [comment]
> Logs says me that, my plugin doesn't has a `IOpenModPlugin` implementation, but, honestly, its just unable to get the access to the signature i.e its unable to resolve LiteDB.dll as I guess.
> 
> [OpenMod.Core.Plugins.PluginAssemblyStore] No IOpenModPlugin implementation found in assembly: UnturnedGuard.OpenMod-73c45b, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null; skipping loading of this assembly as plugin
> 
> ```cs
> using OpenMod.Core.Plugins;
> [assembly: PluginMetadata("UnturnedGuard")]
> namespace UnturnedGuard.OpenMod;
> public class UnturnedGuardPlugin : OpenModUniversalPlugin, IOpenModPlugin
> {
>     private readonly ILiteDatabase _liteDatabase;
>     public UnturnedGuardPlugin(
>         ILiteDatabase liteDatabase,
>         IServiceProvider serviceProvider) : base(serviceProvider)
>     {
>         _liteDatabase = liteDatabase;
>     }
>     protected override Task OnUnloadAsync()
>     {
>         _liteDatabase.Dispose();
>         return Task.CompletedTask;
>     }
> }
> ```
> 
> * After adding the LiteDB.dll into the plugins dir everything goes fine.
> 
> It's kind of weird a bit, I was a little confused at first, would be great to give more information in logs, just in case.
Did you register litedb as a plugin ? I saw that you are injecting it on your plugin
