### ISSUE TITLE
config.yaml / translations.yaml does not contain assembly name in assembly

### ISSUE THREAD

**Issue by Bermingen** [openmod/openmod#664]
csproj
```csproj
<ItemGroup Condition=" '$(Configuration)' == 'Production' ">
  <EmbeddedResource LogicalName="translations.yaml" Include="translations-pro.yaml" />
  <EmbeddedResource LogicalName="config.yaml" Include="config-pro.yaml" />
</ItemGroup>
<ItemGroup Condition=" '$(Configuration)' == 'Demo' ">
  <EmbeddedResource LogicalName="translations.yaml" Include="translations-free.yaml" />
  <EmbeddedResource LogicalName="config.yaml" Include="config-free.yaml" />
</ItemGroup>
```

Logs by openmod
```
translations.yaml does not contain assembly name in assembly: UnturnedGuard.OpenMod. <AssemblyName> and <RootNamespace> must be equal inside your plugins .csproj file
config.yaml does not contain assembly name in assembly: UnturnedGuard.OpenMod. <AssemblyName> and <RootNamespace> must be equal inside your plugins .csproj file
```
Root screenshot of project
![image](https://user-images.githubusercontent.com/114731754/226448003-8d7cba08-7a42-44a3-8e07-54db22f5c272.png)

Even when getting such weird warning I'm still able to get access to the folder of the plugin, etc
![image](https://user-images.githubusercontent.com/114731754/226448216-b06c1895-4e4f-41a9-94a3-208177a34fa5.png)
![image](https://user-images.githubusercontent.com/114731754/226448252-b8afd3b4-94bf-414f-a2be-ccfc53d129cb.png)

**Comment by rube200** [comment]
i think the logical name is suppose to be `UnturnedGuard.OpenMod.config.yaml`.
Om always try to extract EmbeddedResources but it throws a warning when it not contains AssemblyName.
(In normal use case the simple case of just including it without LogicalName)

https://github.com/openmod/openmod/blob/f797e3750b2537cd3b19d9da0038fbd4c4060c69/framework/OpenMod.Core/Helpers/AssemblyHelper.cs#L41-L49

**Comment by Bermingen** [comment]
Thanks again, works great
