### ISSUE TITLE
openmod isn't loading

### ISSUE THREAD

**Issue by 0x59R11** [openmod/openmod#671]
![image](https://user-images.githubusercontent.com/41921371/228111985-dc0bfa51-270b-49f2-baaa-99142f85cc78.png)
![image](https://user-images.githubusercontent.com/41921371/228111815-8184b9fc-b30f-476f-be31-f8fc55d212b5.png)

**Comment by rube200** [comment]
Im not sure what are you trying to do but i dont think that problem is on Om side.
But just in case re-install Om.
