### ISSUE TITLE
Did you forget to add [Service] to your interfaces?

### ISSUE THREAD

**Issue by sunnamed434** [openmod/openmod#678]
```console
[OpenMod.Runtime.OpenModStartup] Type UnturnedGuard.OpenMod.Services.PlayerIgnoreChecker in assembly UnturnedGuard.OpenMod-6ac430, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null has been marked as ServiceImplementation but does not inherit any services!
Did you forget to add [Service] to your interfaces?
```

What if I don't need the interfaces and have only a class?

Is there a way to kinda don't see those warnings?

**Comment by sunnamed434** [comment]
Maybe a suppress attribute on the over-service attribute can be added to remove warnings from the console?

Suggesting:
[SupressServiceNoInterface]

What do you think?

**Comment by CyberAndrii** [comment]
> What if I don't need the interfaces and have only a class?

This is against dependency injection best practices (will led to a tightly coupled code). But for exceptions it can be registered  manually in IServiceConfigurator or IPluginServiceConfigurator.
