### ISSUE TITLE
IPluginServiceConfigurationContext Add access to the IRuntime and plugin working directory

### ISSUE THREAD

**Issue by sunnamed434** [openmod/openmod#681]
i.e 

```cs
var runtime = context.ParentLifetimeScope.Resolve<IRuntime>();
var runtimeWorkingDirectory = runtime.WorkingDirectory;
// get path to the plugin directory
// etc etc etc
```

**Comment by CyberAndrii** [comment]
Would make sense.

Working directory can be passed to constructor here https://github.com/openmod/openmod/blob/25c580054dad3f7658cb3c99838175c38a9aa27a/framework/OpenMod.Core/Plugins/PluginActivator.cs#L197

Not sure about `IRuntime` as you can already get it as shown in your example.

**Comment by sunnamed434** [comment]
> Not sure about `IRuntime` as you can already get it as shown in your example.

Yeah, I agree, but, it doesn't give a dev visibility that they can do that, etc
