### ISSUE TITLE
StopWatch alternative

### ISSUE THREAD

**Issue by sunnamed434** [openmod/openmod#698]
I saw that OpenMod uses StopWatch to get the difference between the time, and the old .NET Framework doesn't provide a new API for the StopWatch, so, I already use a new stopwatch from the newest .NET Versions (6.0), here's the code and examples:

What do you think, do we need to replace the actual StopWatch with this, because as far as I know this version of StopWatch does minimum allocations

```cs
public static class StopwatchUtilities
{
    private const long TicksPerMillisecond = 10000;
    private const long TicksPerSecond = TicksPerMillisecond * 1000;
    
    public static TimeSpan GetElapsedTime(long startingTimestamp, long endingTimestamp)
    {
        var tickFrequency = (double)TicksPerSecond / Stopwatch.Frequency;
        return new TimeSpan((long)((endingTimestamp - startingTimestamp) * tickFrequency));
    }
}
```

Example of how to use it:

```cs
private long _startTime;

_startTime = Stopwatch.GetTimestamp();
var res = 2 + 2; //do some operations
TimeSpan elapsedTime = StopwatchUtilities.GetElapsedTime(_startTime, Stopwatch.GetTimestamp());
```

**Comment by DiFFoZ** [comment]
OpenMod uses only 1 StopWatch to get total execution time of a command. Creating for that stopwatch utility is no point.
