### ISSUE TITLE
OpenMod.Unturned.Redist accessibility modifier

### ISSUE THREAD

**Issue by sunnamed434** [openmod/openmod#701]
Instead of just copying the files from Unturned into the Redist of the OpenMod - The idea is always to upload the Redist of Unturned and change the member's accessibility:
- Private fields, properties, etc, and make them public, and only then upload the redist

Since reflection is not always the best way to access something hidden by the Unturned code, and it will slow the plugin a lot.

If you like the idea I could make an application that will modify the code of Unturned to make the code more public, using assembly manipulators such as AsmResolver, also if you want we could upload this application by the name of the OpenMod, If someone wants to contribute in this application I will only be glad.

But, just to make such an application is not enough, need to promote this topic for OpenMod contributors, due to there's no reason to use this application if Redist is updating very rarely or just without the _"accessibility modifier"_

### Example

Standard way

```cs
var startedUse = (float)typeof(UseableThrowable)
            .GetField("startedUse", BindingFlags.Instance | BindingFlags.NonPublic)!
            .GetValue(useable);
```

or with used _"accessibility modifier"_ on OpenMod.Unturned.Redist

```cs
var startedUse = useable.startedUse;
```

What do you think about that?

**Comment by Trojaner** [comment]
I don't think this would work without replacing Assembly-CSharp etc. as file too

**Comment by sunnamed434** [comment]
> I don't think this would work without replacing Assembly-CSharp etc. as file too

Do you mean replacing the Assembly-CSharp on the server side, if it is, this is unnecessary 
It will work for Plugin Development usage, I already tested it

Replacing the Assembly-CSharp file in the Redist is enough

**Comment by DiFFoZ** [comment]
IMO a big NO. Making everything public will result to devs to use internal things that updates frequently and without backwards compatibility. 

This should be only decided by the dev that they will use it with caution. Just as I use the publicizer in Dummy plugin with caution:
https://github.com/EvolutionPlugins/Dummy/blob/0f51c93d1cbd035ccad6e2b653076b5350543f00/Dummy/Dummy.csproj#L37-L45

**Comment by CyberAndrii** [comment]
This will lead to runtime exceptions unless unsafe code is enabled. The library mentioned by DiFFoZ is the way to go.
