### ISSUE TITLE
Openmod making servers to crash on latest Unturned v3.23.7

### ISSUE THREAD

**Issue by ItsRodrigoAl** [openmod/openmod#702]
Having Openmod installed with the latest game version, if you try to use certain commands it will make the server crash

Here's the log, it makes the server crash even with trying to use the command /i from Rocketmod. I tried using the same commands without Openmod and it worked well, so is due to Openmod
![image](https://github.com/openmod/openmod/assets/57012631/a007aeaf-e5d6-45ed-bf20-b8f779ccf824)

**Comment by DiFFoZ** [comment]
Sadly, I cannot reproduce it on my Windows server

**Comment by ItsRodrigoAl** [comment]
> 

How can I help to make the fix faster? All i know is that some commands from rocketmod will make crash the server only if Openmod is installed. The easier one is trying to use /i from rocketmod. This only happens when having Rocket and Openmod at same time. If Openmod is uninstalled, those commands won't make crash the server

**Comment by rube200** [comment]
can you upload the crash information??

**Comment by ItsRodrigoAl** [comment]
> can you upload the crash information??

thats everything it shows up. here are some logs

[Server_unturned.log](https://github.com/open
[crash-2023-05-26 16_29_11.log](https://github.com/openmod/openmod/files/11578580/crash-2023-05-26.16_29_11.log)
mod/openmod/files/11578579/Server_unturned.log)

**Comment by rube200** [comment]
Hmmm, can you also upload dump file

**Comment by DiFFoZ** [comment]
The crash was caused by plugins
