### ISSUE TITLE
Obsolete LocationNode

### ISSUE THREAD

**Issue by rube200** [openmod/openmod#709]
Todo: Update command LocationNodeProvider
https://github.com/openmod/openmod/blob/main/unturned/OpenMod.Unturned/Locations/UnturnedLocationCommandParameterResolveProvider.cs

**Comment by DevInc0** [comment]
Should we just remove `type == typeof(LocationNode)` from `Supports` method?

https://github.com/openmod/openmod/blob/efd15044ac5708d92d4fe56e199300265a82799e/unturned/OpenMod.Unturned/Locations/UnturnedLocationCommandParameterResolveProvider.cs#L17-L20

And also remove type check from `ResolveAsync`

https://github.com/openmod/openmod/blob/efd15044ac5708d92d4fe56e199300265a82799e/unturned/OpenMod.Unturned/Locations/UnturnedLocationCommandParameterResolveProvider.cs#L45-L48
