### ISSUE TITLE
DisposeAllAsync using List instead of IEnumerable

### ISSUE THREAD

**Issue by sunnamed434** [openmod/openmod#712]
This will make minimum heap allocation and improve the openmod by performance a lot

One of the issues in the code while disposing of scopes in the event bus: [see](https://github.com/openmod/openmod/blob/00be4e9ded81a7e1da6915af1721360723fe0981/framework/OpenMod.Core/Eventing/EventBus.cs#L450)

Before (code in openmod now, see [here](https://github.com/openmod/openmod/blob/00be4e9ded81a7e1da6915af1721360723fe0981/framework/OpenMod.Core/Helpers/DisposeHelper.cs))
```cs
public static async Task DisposeAllAsync(this IEnumerable<object> objects)
{
    foreach (var @object in objects)
    {
        if (@object is IAsyncDisposable asyncDisposable)
        {
            await asyncDisposable.DisposeAsync();
        }
        else if (@object is IDisposable disposable)
        {
            disposable.Dispose();
        }
    }
}
```

Code example:
```cs
public static async Task DisposeAllAsync(this List<object> objects)
{
    for (var i = 0; i < objects.Count; i++)
    {
        var @object = objects[i];
        if (@object is IAsyncDisposable asyncDisposable)
        {
            await asyncDisposable.DisposeAsync();
        }
        else if (@object is IDisposable disposable)
        {
            disposable.Dispose();
        }
    }
}
```

**Comment by Trojaner** [comment]
The speed difference between for and foreach is insignificant.

**Comment by sunnamed434** [comment]
> The speed difference between for and foreach is insignificant.

yeah, it will doesn't play much, but those changes are prevents using the IEnumerable - this will play a lot

**Comment by Trojaner** [comment]
Why?

**Comment by sunnamed434** [comment]
The thing I know is that `for` can be a bit faster, and when I see that this is a List, not a IEnumerable I always try to use for instead of foreach, and also don't use the yield return which allocates the memory on the heap

I Prefer for loops over foreach when heap-allocated enumerators can be avoided. For example, if GetEnumerator returns a non-struct type enumerator, but accessing elements by an index is possible, use a for loop with an indexer variable

See one of the my [benchmarks](https://sunnamed434.github.io/posts/c-code-optimization-tricks/#foreach-ienumerable-vs-list)

**Comment by rube200** [comment]
https://sunnamed434.github.io/posts/c-code-optimization-tricks/#list-foreach-vs-for
This one seems wrong, you loop the list on both but you on the for never get the value using the index

**Comment by sunnamed434** [comment]
So, what do you think does openmod need this refactoring and optimization?

**Comment by rube200** [comment]
You should test it first, and if that increases place a PR with performance screenshoots

**Comment by DiFFoZ** [comment]
DisposeAllAsync is only used once on shutdown, I'm thinking that this change will be not significant
