### ISSUE TITLE
Unturned Commands

### ISSUE THREAD

**Issue by rube200** [openmod/openmod#72]
Default unturned commands do not appear to be working correctly.
![Captura de Ecrã (57)](https://user-images.githubusercontent.com/20555316/85960290-5592af00-b99a-11ea-9212-b4aea6696077.png)
The one that seems to "work" shows '1 1 1' in the chat with green color

**Comment by Trojaner** [comment]
Should be fixed now, can you confirm?

**Comment by rube200** [comment]
i will
