### ISSUE TITLE
Zombies have a lot of armor multiplier on Horde Beacons

### ISSUE THREAD

**Issue by ItsRodrigoAl** [openmod/openmod#721]
Now after the latest Unturned updates, for information i've saw seems like Nelson updated some stuff with the Zombie Manager or something like that. Anyway, now when making an Horde Beacon in solo, instead of 2 headshots, zombies takes 3 headshots (weird), but if you try to make the horde with a friend, this is increased to 10 headshots, and this is even worse with more people on the horde, so if you make a horde beacon with 4 more friends, zombies takes like 60 headshots to be killed, and the final mega can not be killed

I know this is caused by openmod because i tried to make an horde without openmod and this was not happening. then I installed it again and the bug started to happen. even I used an "old" and the latest openmod version, and still happening with both

**Comment by Corbyncc** [comment]
This is not an OpenMod issue.

**Comment by CyberAndrii** [comment]
It might be. OpenMod [copies](https://github.com/openmod/openmod/blob/877803b90fb376a0aa8f2e12bb36f3a2c171f22a/unturned/OpenMod.Unturned/Zombies/Events/ZombieEventsListener.cs#L88..L107) some damage calculation code from Unturned. If it has been changed, then we need to update it as well.

**Comment by Corbyncc** [comment]
> It might be. OpenMod [copies](https://github.com/openmod/openmod/blob/877803b90fb376a0aa8f2e12bb36f3a2c171f22a/unturned/OpenMod.Unturned/Zombies/Events/ZombieEventsListener.cs#L88..L107) some damage calculation code from Unturned. If it has been changed, then we need to update it as well.

My apologies, it looks like you are correct.
