### ISSUE TITLE
MySQL issues since the latest OM updates

### ISSUE THREAD

**Issue by ItsRodrigoAl** [openmod/openmod#722]
DropBoxes by RestoreMonarchy, RocketMod
![image](https://github.com/openmod/openmod/assets/57012631/4d605eb9-4eac-4c57-9849-8d002f8279ec)

GlobalBan by Pustalorc, OpenMod
![image](https://github.com/openmod/openmod/assets/57012631/659821e7-524b-4c57-a7c6-62122ebab843)
His answer (not sure what did he tried to say tbh)
![image](https://github.com/openmod/openmod/assets/57012631/dda54709-fdff-457e-8e53-f761409dc87d)

I've just started receiving those bugs with RM And OM plugins since the latest OM update, and this was not happening on the previous OM version (actually I'm using the version v3.3.15, which is an "old one" since I don't have those problems with it). I have no idea if I can fix it by myself, I know Pusta is a great dev and he didn't said something like he had to update his plugin, and my mysql version is already updated from what I know (v8.0.30)

**Comment by sunnamed434** [comment]
After the latest OM release the om wont even load anymore, no logs, nothing, I'm using RocketMod + OM
