### ISSUE TITLE
About openmod reload, hot reload optimization

### ISSUE THREAD

**Issue by Sugobet** [openmod/openmod#732]
I suggest that openmod hot reload should target a single plugin,

Example: openmod reload \<MyOpenModPluginName\>

Now, hot reload will reload all plugins, which will cause some important plugins to stop working

**Comment by Trojaner** [comment]
OpenMod does not support reloading specific plugins as it uses inversion of control and dependency injection. Most we can do is force reload the plugin's configuration but most plugins should support auto-reloading as soon as the config is saved.
