### ISSUE TITLE
OnPluginKeyTick shared key status

### ISSUE THREAD

**Issue by DevInc0** [openmod/openmod#745]
Ran into non-critical bug on my server. When any player presses any plugin key, it presses for every player on the server.

I believe the reason behind it is that `PlayerInputEventsListener` shares key statuses.

Let's say we have player Bob and Tom.

And if player Bob will press the plugin key, then its value will be stored in `m_LastInputs`. And, as it shares the values between all players, then the same value will be for player Tom.

https://github.com/openmod/openmod/blob/19e1412759ee5c5c300eb0123ba31ec7a069de2c/unturned/OpenMod.Unturned/Players/Input/Events/PlayerInputEventsListener.cs#L27-L47

**Comment by DevInc0** [comment]
I believe the best solution is to replace `bool[] m_LastInputs` with  `Dictionary<CSteamID, bool[]> m_LastInputs` which will store inputs for each player.

And also adding and removing `KeyValuePair<CSteamID, bool[]>` to/from `m_LastInputs` with `Provider.onServerConnected` and `Provider.onServerDisconnected`

May I create a pull request to fix this issue?

**Comment by DiFFoZ** [comment]
> And also adding and removing KeyValuePair<CSteamID, bool[]> to/from m_LastInputs with Provider.onServerConnected and Provider.onServerDisconnected

I suggest changing the type of event listener to `IUnturnedPlayerEventsListener` to not subscribing to `Provider.onServerConnected` and `Provider.onServerDisconnected`.

Yes, you may create a pull request.
