### ISSUE TITLE
Yaml `System.Numerics.Vector3` built-in converter

### ISSUE THREAD

**Issue by DevInc0** [openmod/openmod#759]
Found out after some additional investigation that there's no built-in converter for `System.Numerics.Vector3` in YamlDotNet.

But I believe that a lot of developers will need an ability to store `System.Numerics.Vector3` in configurations, data files, etc. 

And it would be bad for them to find that they have to figure out a workaround for this by themselves.

So shall we create a built-in `System.Numerics.Vector3` yaml converter for OpenMod? 

I can create a PR for that if there will be an approvement of my suggestion.

**Comment by Trojaner** [comment]
Sounds like a good idea to me

**Comment by DiFFoZ** [comment]
And made it configurable via `IOptions`, just like [SmartFormatOptions](https://github.com/openmod/openmod/blob/main/framework/OpenMod.Core/Localization/SmartFormatOptions.cs)

**Comment by DevInc0** [comment]
> And made it configurable via `IOptions`, just like [SmartFormatOptions](https://github.com/openmod/openmod/blob/main/framework/OpenMod.Core/Localization/SmartFormatOptions.cs)

But what exactly do you mean by "configurable"? The way how or where it stores the vector?

I thought about simple `IYamlTypeConverter` and additional `WithTypeConverter()` method at:

https://github.com/openmod/openmod/blob/6860e891709de05fb9d121cfd838088302c96951/framework/OpenMod.Core/Persistence/YamlDataStore.cs#L62-L72

**Comment by DiFFoZ** [comment]
By configurable, I mean that it's easy to add/remove `IYamlTypeConverter` without the changes on OpenMod side
