### ISSUE TITLE
Instead of using file scoped usings use global usings

### ISSUE THREAD

**Issue by sunnamed434** [openmod/openmod#773]
It will improve code readability, and also what do you think about not using a block-scoped namespace and instead using a file-scoped namespace?

Before:
```cs
using ..
...
...

namespace OpenMod.Core.Commands.OpenModCommands
{
// code...
}
```

After:
```cs
namespace OpenMod.Core.Commands.OpenModCommands;
```

**Comment by DiFFoZ** [comment]
Refactoring every file is not in priority, but you can use the file-scoped namespace for new classes or when refactoring the old class.
