### ISSUE TITLE
Set Unturned projects `Prefer32Bit` to false

### ISSUE THREAD

**Issue by sunnamed434** [openmod/openmod#778]
Since Unturned doesn't support 32-bit for a long time, there's no need to do extra work

.csproj
```csproj
<Prefer32Bit>false</Prefer32Bit>
```

**Comment by sunnamed434** [comment]
to avoid unnecessary work and compiler optimizations

**Comment by sunnamed434** [comment]
For example, see [here](https://stackoverflow.com/questions/12066638/what-is-the-purpose-of-the-prefer-32-bit-setting-in-visual-studio-and-how-does#:~:text=When%20using%20the%20%22Prefer%2032,compiled%20to%20x86%20machine%20code.)

**Comment by DiFFoZ** [comment]
It is already by default set to `false`, see https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L115
