### ISSUE TITLE
Openmod crash

### ISSUE THREAD

**Issue by Senior-S** [openmod/openmod#78]
Hello, today i installed openmod (0.9.42) in my server, the first load work without problem, when it finish i trying to install the rocketmod bridge and the command dont send me any feedback, i restarted the server and now openmod always crash.

Log: https://pastebin.com/FKtAw1KY

In my modules folder i have Openmod and AviRockets.

**Comment by rube200** [comment]
Same where without Avi

**Comment by Senior-S** [comment]
> 
> 
> Same where without Avi

Ok, so it's a error from the module?

**Comment by rube200** [comment]
Yes, when module initialize/start

**Comment by Senior-S** [comment]
> 
> 
> Yes, when module initialize/start

Ok, thanks for answer, i will wait to the next version and hope it fixed the error.
