### ISSUE TITLE
The server shutdown command was randomly and automatically executed

### ISSUE THREAD

**Issue by y1meng** [openmod/openmod#805]
I don't understand why the shutdown command was automatically executed when the server was just started. I checked that the automatic task of openmod was not enabled.But it seems to be a random behavior that only occurs once in a long time.
![image](https://github.com/openmod/openmod/assets/45099938/6b97f068-1be5-4290-96e4-26a6241e4016)
![image](https://github.com/openmod/openmod/assets/45099938/2a28dd48-b8b2-424b-ad2b-20aaede94b18)

**Comment by rube200** [comment]
Can you enable debug and post full log?

**Comment by y1meng** [comment]
> Can you enable debug and post full log?

This issue has reoccurred, and I cannot distinguish whether it is an issue with an untrurned or openmod. This is the complete log, but I am not sure how to enable debug mode

**Comment by y1meng** [comment]
[nohup.txt](https://github.com/openmod/openmod/files/13768890/nohup.txt)
[openmod-2023-12-26-03-00-38.txt](https://github.com/openmod/openmod/files/13768891/openmod-2023-12-26-03-00-38.txt)

**Comment by y1meng** [comment]
Sorry, I have confirmed that my external API accidentally triggered the shutdown command. I can troubleshoot the issue with my own plugin
