### ISSUE TITLE
Ctrl-C doesn't shutdown server

### ISSUE THREAD

**Issue by Trojaner** [openmod/openmod#82]
.NET Generic host handles first Ctrl-C - which shuts down OpenMod. Only the second Ctrl-C shuts down Unturned.

**Comment by rube200** [comment]
Maybe make the game module to register the shutdown event/action to be called when the runtime is shut down

**Comment by Trojaner** [comment]
Need to call Provider.shutdown when the IHostApplicationLifeTime.ApplicationStopped event occurs

**Comment by rube200** [comment]
Exactly but which game Will have the own shutdown
