### ISSUE TITLE
New version issues

### ISSUE THREAD

**Issue by ItsRodrigoAl** [openmod/openmod#822]
So, I installed the 3.7.5 via command but it made the module not starting wit the server. So I tried installing it manually and it worked! But if I try to update again to newer versions (like the 3.8.3) it just won't work, even if with commands or manually.

The last version which is actually working is the 3.7.6, since I installed it manually after the 3.7.5 and it worked fine, but with the 3.8+ versions it won't just work

**Comment by ItsRodrigoAl** [comment]
I want to add that since the last Unturned update, I've noticed an issue with a plugin I use for OpenMod, which leads to crash the server when loading with openmod **sometimes**. This was not happening before, and I would want to know if this is an issue with the plugin or openmod since the last game update? Starting the server may crash or not when loading the plugin when openmod is loading, is so weird
![image](https://github.com/openmod/openmod/assets/57012631/36836bed-0f13-4f77-8ffc-e91e0bb39035)

**Comment by HathHub** [comment]
Those versions are broken, check discord

**Comment by ItsRodrigoAl** [comment]
Yeah I cant they banned me from om discord for saying ustore was better than imperial

**Comment by rube200** [comment]
Sounds like a you problem.
OM discord is not related to IP or Ustore, so dont bring it up

**Comment by ItsRodrigoAl** [comment]
> "OM discord is not related to IP or Ustore, so dont bring it up"

Say it to Trojaner for banning me from OM/IP discords, not to me :P

**Comment by Trojaner** [comment]
> > "OM discord is not related to IP or Ustore, so dont bring it up"
> 
> Say it to Trojaner for banning me from OM/IP discords, not to me :P

Want me to extend it to GitHub as well?

**Comment by ItsRodrigoAl** [comment]
> Want me to extend it to GitHub as well? You are banned there for reasons.

Nah I just want you to unban me from at least OpenMod discord. Was no sense to get banned from there when "the main discussion" was just only from the ImperialPlugins discord, also I do constantly report issues here on the OpenMod github since I'm actively using it and testing things

Discord: rodrigo_al_
