### ISSUE TITLE
UnturnedUserProvider is not disposing

### ISSUE THREAD

**Issue by DiFFoZ** [openmod/openmod#92]

**Comment by Trojaner** [comment]
I just checked this yesterday, it was disposing. But for some reason it's events get called twice.

**Comment by DiFFoZ** [comment]
Just checked. Is not disposing
![image](https://user-images.githubusercontent.com/48765566/86531057-4a82d600-bee8-11ea-834a-a6a768eeb8bf.png)

And shutdown also doesn't dispose
![image](https://user-images.githubusercontent.com/48765566/86531086-887ffa00-bee8-11ea-821d-4d7b1ce3d9f9.png)

**Comment by Trojaner** [comment]
A lot of stuff seems to be disposing twice according to your logs, hm..

**Comment by DiFFoZ** [comment]
![image](https://user-images.githubusercontent.com/48765566/86702481-34d2f500-c03d-11ea-947b-01e50880fda3.png)

`Autofac.Core.Disposer` is dispose of `UserManager` twice.. weird
