### ISSUE TITLE
Console Input is glitching after reloading openmod

### ISSUE THREAD

**Issue by DiFFoZ** [openmod/openmod#93]
![image](https://user-images.githubusercontent.com/48765566/86530401-a21e4300-bee2-11ea-8206-8ea1a26bfd56.png)

**Comment by DiFFoZ** [comment]
I think because host creating new `SerilogConsoleInputOutput`, but old doesn't dispose

**Comment by Trojaner** [comment]
You are right, thats likely the case. Need to store previous ioHandlers and restore them when OpenModUnturnedHost gets disposed
